apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- patch-trustyai-configmap-job.yaml

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/hook: PreSync

configMapGenerator:
  - name: patch-trustyai-configmap
    namespace: redhat-ods-applications
    files:
      - patch-trustyai-configmap.sh
